from typing import Protocol


class EngineRuntime(Protocol):
    """Port implemented by a project-scoped collection of local engines."""

    def agent(self, member, name, instructions, native_id=None): ...
    def models_for(self, engine_id): ...
    def status(self): ...
    def stop(self): ...
