from typing import Protocol


class EngineRuntime(Protocol):
    """Port implemented by a project-scoped collection of local engines."""

    def agent(self, member, name, instructions, native_id=None): ...
    def agent_lock(self, member_id): ...
    def has_agent(self, member_id): ...
    def is_current(self, member_id, agent): ...
    def reset_agent(self, member_id): ...
    def models_for(self, engine_id): ...
    def status(self): ...
    def stop(self): ...
