from typing import Protocol


class ProjectRepository(Protocol):
    """Project metadata and lifecycle persistence contract."""

    def load_all(self): ...
    def save(self, project): ...
    def archive(self, project): ...
    def erase(self, project): ...
    def erase_session(self, project, session): ...
    def storage(self, project, session=None): ...
