from typing import Protocol


class StateRepository(Protocol):
    """Persistence operations required by conversation orchestration."""

    def messages(self, project, session): ...
    def message_page(self, project, session, before=None, after=None,
                     anchor=None, limit=60, search=None): ...
    def session_metrics(self, project, session): ...
    def append(self, project, session, message): ...
    def commit_message(self, project, session, message): ...
    def mark_read(self, project, session, seq): ...
    def checkpoints(self, project, session): ...
    def save_checkpoint(self, project, session, seat_id, checkpoint): ...
    def clear_checkpoints(self, project, session): ...
    def save_project(self, project): ...
    def agent_contexts(self, project): ...
    def save_agent_context(self, project, member_id, checkpoint): ...
    def clear_context_history(self, project, session, boundary_seq=None): ...
