from typing import Protocol


class TranscriptRepository(Protocol):
    """Durable ordered messages, paging and context-history cleanup."""

    def append(self, project, session, message): ...
    def messages(self, project, session): ...
    def page(self, project, session, before=None, after=None, anchor=None,
             limit=60, search=None): ...
    def metrics(self, project, session): ...
    def clear(self, project, session): ...
    def clear_closed(self, project, session, boundary_seq=None): ...
