document.documentElement.dataset.theme=localStorage.getItem('sinaxa-theme')||'dark';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
let data={},projectId=null,sessionId=null,selected=new Set(),pending=[],poll=null;
const project=()=>data.projects?.find(x=>x.id===projectId), session=()=>project()?.sessions.find(x=>x.id===sessionId);
const member=id=>data.members?.find(x=>x.id===id), seat=id=>data.seats?.find(x=>x.id===id);
async function api(path,options={}){let r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});let body=await r.json();if(!r.ok)throw Error(body.error||r.statusText);return body}
function body(value){return JSON.stringify(value)}
async function refresh(){let q=new URLSearchParams();if(projectId)q.set('project',projectId);if(sessionId)q.set('session',sessionId);if($('search').value)q.set('search',$('search').value);data=await api('/api/state?'+q);if(!projectId&&data.projects?.length)projectId=data.projects[0].id;let p=project();if(p&&!sessionId)sessionId=p.sessions.find(x=>x.kind==='team')?.id;if(sessionId&&!p?.sessions.some(x=>x.id===sessionId))sessionId=p?.sessions.find(x=>x.kind==='team')?.id||null;if(projectId&&(data.project!==projectId||data.session!==sessionId))return refresh();render()}
function render(){renderProjects();renderSeats();renderSessions();renderConversation()}
function renderProjects(){$('projects').innerHTML=(data.projects||[]).map(p=>`<div class="project ${p.id===projectId?'active':''}" data-project="${p.id}"><span><i class="dot ${p.state}"></i>${esc(p.name)}</span><small>${p.state}</small></div>`).join('');document.querySelectorAll('[data-project]').forEach(n=>n.onclick=()=>{projectId=n.dataset.project;sessionId=null;selected.clear();refresh()});let p=project();$('projectTitle').textContent=p?.name||'Projects';$('projectState').textContent=p?`${p.state} · ${size(p.storage)}`:'';$('toggleProject').textContent=p?.state==='open'?'Close project':'Open project';$('toggleProject').disabled=!p;$('newSession').disabled=!p;$('newSessionSmall').disabled=!p;$('newSeat').disabled=!p}
function renderSeats(){$('seats').innerHTML=(data.seats||[]).map(s=>{let m=member(s.occupant);return `<div class="seat ${selected.has(s.id)?'selected':''}" data-seat="${s.id}" title="Click: direct session · ⌘/Ctrl-click: select · Double-click: edit"><span class="check">${selected.has(s.id)?'✓':''}</span><b>${esc(s.role)}</b><small>${esc(m?.name||'Unassigned')}</small></div>`}).join('');document.querySelectorAll('[data-seat]').forEach(n=>{n.onclick=e=>{let id=n.dataset.seat;if(e.metaKey||e.ctrlKey){selected.has(id)?selected.delete(id):selected.add(id);return renderSeats()}selected=new Set([id]);let direct=project()?.sessions.find(x=>x.kind==='direct'&&x.participants[0]===id);if(direct){sessionId=direct.id;refresh()}};n.ondblclick=()=>editSeat(n.dataset.seat);n.oncontextmenu=e=>{e.preventDefault();if(!selected.has(n.dataset.seat))selected=new Set([n.dataset.seat]);renderSeats();createSession()}})}
function renderSessions(){$('sessions').innerHTML=(project()?.sessions||[]).filter(x=>!x.archived).map(s=>`<div class="session ${s.id===sessionId?'active':''} ${s.kind!=='custom'?'managed':''}" data-session="${s.id}">${esc(s.name)}<small> · ${s.participants.length}</small></div>`).join('');document.querySelectorAll('[data-session]').forEach(n=>n.onclick=()=>{sessionId=n.dataset.session;selected.clear();refresh()})}
function renderConversation(){let p=project(),s=session();$('sessionTitle').textContent=s?.name||'Select a project';$('participants').innerHTML=s?s.participants.map(id=>{let x=seat(id),m=x&&member(x.occupant);return x?`<span class="person"><i style="background:${m?.colour||'var(--seat)'}">${esc((x.name||'?')[0])}</i>${esc(x.name)}<small>${esc(x.role)}</small></span>`:''}).join(''):'';$('composer').style.display=s&&p?.state==='open'&&!s.archived?'':'none';$('clearContext').disabled=!s;$('sessionMenu').disabled=!s;$('clearSession').disabled=!s||!!data.status?.busy?.length;let messages=data.messages||[];$('messages').innerHTML=!s?'<div class="empty">Choose a project to see its seats and sessions.</div>':!messages.length?'<div class="empty">This session is empty. Send a message to begin.</div>':messages.map(m=>m.kind==='boundary'?`<div class="boundary">${esc(m.text)}</div>`:`<article class="message ${m.kind==='error'?'error':''}"><div class="avatar">${esc((m.author_name||'?')[0])}</div><div><div class="meta"><b>${esc(m.author_name)}</b><time>${new Date(m.ts*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div><div class="body">${format(m.text)}</div>${images(m)}</div></article>`).join('');let box=$('messages');box.scrollTop=box.scrollHeight}
function format(text){return esc(text).replace(/```([\s\S]*?)```/g,'<pre>$1</pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<b>$1</b>')}
function images(m){return (m.images||[]).length?`<div class="shots">${m.images.map(name=>`<img src="/api/files/${name}?project=${projectId}&session=${sessionId}">`).join('')}</div>`:''}
function size(n=0){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function form(title,html,onSave){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;let d=$('dialog');d.showModal();d.onclose=async()=>{if(d.returnValue!=='default')return;try{await onSave(new FormData(d.querySelector('form')));refresh()}catch(e){alert(e.message)}}}
function memberOptions(value=''){return `<option value="" ${!value?'selected':''}>Unassigned</option>`+(data.members||[]).filter(x=>x.kind!=='human').map(m=>`<option value="${m.id}" ${m.id===value?'selected':''}>${esc(m.name)}</option>`).join('')}
function typeOptions(){return (data.project_types||[]).map(type=>`<option value="${type.id}" ${type.id==='type_blank'?'selected':''}>${esc(type.name)} · ${type.seat_templates.length} seats</option>`).join('')}
function newProject(){form('New project',`<label>Name<input name="name" required></label><label>Project type<select name="type_id">${typeOptions()}</select></label><label>Working folder<input name="cwd" placeholder="Use Sinaxa folder"></label>`,f=>api('/api/projects',{method:'POST',body:body({name:f.get('name'),cwd:f.get('cwd')||null,type_id:f.get('type_id')||null})}).then(x=>{projectId=x.project.id;sessionId=null}))}
function newSeat(){form('Add seat',`<label>Role<input name="role" required></label><label>Member<select name="occupant">${memberOptions()}</select></label><label>Instructions<textarea name="prompt" required></textarea></label>`,f=>api('/api/seats',{method:'POST',body:body({project:projectId,role:f.get('role'),occupant:f.get('occupant'),prompt:f.get('prompt')})}))}
function editSeat(id){let s=seat(id);form('Edit seat',`<label>Role<input name="role" value="${esc(s.role)}"></label><label>Member<select name="occupant">${memberOptions(s.occupant)}</select></label><label>Instructions<textarea name="prompt">${esc(s.prompt)}</textarea></label><label class="danger"><input type="checkbox" name="remove"> Remove this seat and its direct history</label>`,f=>f.get('remove')?api(`/api/seats/${id}?project=${projectId}`,{method:'DELETE'}):api('/api/seats/'+id,{method:'PATCH',body:body({project:projectId,role:f.get('role'),occupant:f.get('occupant'),prompt:f.get('prompt')})}))}
function createSession(){if(!projectId)return;let picks=selected.size?[...selected]:(data.seats||[]).map(x=>x.id);form('New session',`<label>Name<input name="name" required></label><div>${(data.seats||[]).map(s=>`<label class="choice"><input type="checkbox" name="participants" value="${s.id}" ${picks.includes(s.id)?'checked':''}> ${esc(s.role)} · ${esc(s.name)}</label>`).join('')}</div>`,f=>api('/api/sessions',{method:'POST',body:body({project:projectId,name:f.get('name'),participants:f.getAll('participants')})}).then(x=>{sessionId=x.session.id;selected.clear()}))}
$('newProject').onclick=newProject;$('newSeat').onclick=newSeat;$('newSession').onclick=createSession;$('newSessionSmall').onclick=createSession;
$('toggleProject').onclick=async()=>{let p=project();await api('/api/projects/'+p.id,{method:'PATCH',body:body({state:p.state==='open'?'closed':'open'})});refresh()};
$('clearContext').onclick=async()=>{await api(`/api/sessions/${sessionId}/context`,{method:'POST',body:body({project:projectId})});refresh()};
$('clearSession').onclick=async()=>{let s=session();if(!s||!confirm(`Clear all messages and attachments from “${s.name}”?\n\nThe session, participants and conversation limits will be kept.`))return;try{await api(`/api/sessions/${s.id}/history`,{method:'POST',body:body({project:projectId})});await refresh()}catch(e){alert(e.message)}};
$('sessionMenu').onclick=()=>{let s=session();form('Manage session',`<p>${esc(s.name)} · ${size(s.storage)}</p><label>Agent response timeout (seconds)<input type="number" name="turn_timeout" min="30" max="7200" value="${s.turn_timeout||1800}"></label><label>Maximum agent turns per round<input type="number" name="max_agent_turns" min="1" max="100" value="${s.max_agent_turns||100}"></label>${s.kind==='custom'?'<label><input type="checkbox" name="archive" '+(s.archived?'checked':'')+'> Archived</label><label class="danger"><input type="checkbox" name="remove"> Delete session and history</label>':''}<label class="danger"><input type="checkbox" name="clear"> Clear history and attachments</label>`,f=>{if(f.get('remove'))return api(`/api/sessions/${s.id}?project=${projectId}`,{method:'DELETE'}).then(()=>sessionId=null);if(f.get('clear'))return api(`/api/sessions/${s.id}/history`,{method:'POST',body:body({project:projectId})});return api('/api/sessions/'+s.id,{method:'PATCH',body:body({project:projectId,turn_timeout:+f.get('turn_timeout'),max_agent_turns:+f.get('max_agent_turns'),...(s.kind==='custom'?{archived:!!f.get('archive')}:{})})})})};
let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);searchTimer=setTimeout(refresh,250)};
$('attach').onclick=()=>$('files').click();$('files').onchange=()=>{pending.push(...$('files').files);renderAttachments()};function renderAttachments(){$('attachments').innerHTML=pending.map((f,i)=>`<span class="attachment">${esc(f.name)} <button data-drop="${i}">×</button></span>`).join('');document.querySelectorAll('[data-drop]').forEach(x=>x.onclick=()=>{pending.splice(+x.dataset.drop,1);renderAttachments()})}
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{let t=$('message'),mark=b.dataset.format,a=t.selectionStart,z=t.selectionEnd;t.setRangeText(mark+t.value.slice(a,z)+mark,a,z,'end');t.focus()});
function readFile(file){return new Promise((ok,bad)=>{let r=new FileReader;r.onload=()=>ok({type:file.type,data:r.result.split(',')[1]});r.onerror=bad;r.readAsDataURL(file)})}
$('send').onclick=async()=>{let text=$('message').value.trim();if(!text&&!pending.length)return;let images=await Promise.all(pending.map(readFile));$('message').value='';pending=[];renderAttachments();await api('/api/say',{method:'POST',body:body({project:projectId,session:sessionId,text,images})});refresh();startPoll()};$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('send').click()}};
function startPoll(){clearInterval(poll);let quiet=0;poll=setInterval(async()=>{let before=(data.messages||[]).length;await refresh();let busy=data.status?.busy?.length;if(!busy&&(data.messages||[]).length===before)quiet++;else quiet=0;if(quiet>2){clearInterval(poll);poll=null}},800)}
refresh();
document.addEventListener('click',e=>{if(e.target.matches('dialog button[value="cancel"]')){e.preventDefault();e.target.closest('dialog').close('cancel')}});
