document.documentElement.dataset.theme=localStorage.getItem('sinaxa-theme')||'dark';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
let data={},projectId=null,sessionId=null,selected=new Set(),pending=[],poll=null;
let transcript=[],hasOlder=false,windowKey='',loadingOlder=false,stickBottom=true;
const project=()=>data.projects?.find(x=>x.id===projectId), session=()=>project()?.sessions.find(x=>x.id===sessionId);
const member=id=>data.members?.find(x=>x.id===id), seat=id=>data.seats?.find(x=>x.id===id);
async function api(path,options={}){let r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});let body=await r.json();if(!r.ok)throw Error(body.error||r.statusText);return body}
function body(value){return JSON.stringify(value)}
async function refresh(){let box=$('messages'),nearBottom=!box||box.scrollHeight-box.scrollTop-box.clientHeight<120,q=new URLSearchParams();if(projectId)q.set('project',projectId);if(sessionId)q.set('session',sessionId);if($('search').value)q.set('search',$('search').value);q.set('limit','60');let fresh=await api('/api/state?'+q);data=fresh;if(!projectId&&data.projects?.length)projectId=data.projects[0].id;let p=project();if(sessionId&&!p?.sessions.some(x=>x.id===sessionId))sessionId=null;if(projectId&&data.project!==projectId)return refresh();if(sessionId&&data.session!==sessionId)return refresh();let key=`${projectId||''}:${sessionId||''}:${$('search').value}`;if(key!==windowKey){transcript=[...(fresh.messages||[])];hasOlder=!!fresh.message_page?.has_more;windowKey=key;stickBottom=true}else{let earliest=transcript[0]?.seq,latestOld=fresh.messages?.[0]?.seq,merged=new Map([...transcript,...(fresh.messages||[])].map(m=>[m.seq,m]));transcript=[...merged.values()].sort((a,b)=>a.seq-b.seq);if(earliest==null||latestOld==null||earliest>=latestOld)hasOlder=!!fresh.message_page?.has_more;stickBottom=nearBottom}data.messages=transcript;render()}
function render(){renderProjects();renderSeats();renderSessions();renderConversation()}
function renderProjects(){let chat='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4z"></path></svg>';$('projects').innerHTML=(data.projects||[]).map(p=>{let active=p.id===projectId,children='';if(active){let team=p.sessions.find(x=>x.kind==='team'),custom=p.sessions.filter(x=>x.kind==='custom'&&!x.archived);let roster=(data.seats||[]).map(s=>{let m=member(s.occupant),direct=p.sessions.find(x=>x.kind==='direct'&&x.participants[0]===s.id);return `<div class="roster-line ${direct?.id===sessionId?'active':''}" data-open-session="${direct?.id||''}" role="button" tabindex="0" title="Open direct session with ${esc(m?.name||s.role)}"><i style="background:${m?.colour||'var(--dim2)'}"></i><span>${esc(s.role)} · ${esc(m?.name||'Unassigned')}</span></div>`}).join('');let customs=custom.map(s=>`<div class="tree-session ${s.id===sessionId?'active':''}" data-open-session="${s.id}">${chat}<strong>${esc(s.name)}</strong><small>${s.participants.length}</small></div>`).join('');children=`<div class="project-tree"><div class="tree-session ${team?.id===sessionId?'active':''}" data-open-session="${team?.id||''}">${chat}<strong>Main</strong><small>${(data.seats||[]).length}</small></div><div class="main-roster">${roster}</div>${customs?'<div class="tree-label">Group sessions</div>'+customs:''}</div>`}return `<div class="project-block"><div class="project ${active&&!sessionId?'active':''}" data-project="${p.id}"><span><i class="dot ${p.state}"></i>${esc(p.name)}</span><small>${p.state}</small></div>${children}</div>`}).join('');document.querySelectorAll('[data-project]').forEach(n=>n.onclick=()=>{projectId=n.dataset.project;sessionId=null;selected.clear();refresh()});document.querySelectorAll('[data-open-session]').forEach(n=>{let open=()=>{if(!n.dataset.openSession)return;sessionId=n.dataset.openSession;selected.clear();refresh()};n.onclick=open;n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}});let p=project();$('projectTitle').textContent=p?.name||'Projects';$('projectState').textContent=p?`${p.state} · ${size(p.storage)}`:'';$('toggleProject').textContent=p?.state==='open'?'Close project':'Open project';$('toggleProject').disabled=!p;$('newSession').disabled=!p;$('newSessionSmall').disabled=!p;$('newSeat').disabled=!p}
function renderSeats(){$('seats').innerHTML=(data.seats||[]).map(s=>{let m=member(s.occupant);return `<article class="overview-seat ${selected.has(s.id)?'selected':''}" data-seat="${s.id}" title="Open direct session"><div class="seat-avatar" style="background:${m?.colour||'var(--seat)'}">${esc((m?.name||s.role||'?')[0])}</div><div class="overview-seat-copy"><strong>${esc(s.role)}</strong><span>${esc(m?.name||'Unassigned')}${m?.kind==='agent'&&m.engine?' · '+esc(m.engine):''}</span></div><button class="seat-edit" data-edit-seat="${s.id}" title="Edit seat" aria-label="Edit ${esc(s.role)}">•••</button></article>`}).join('')||'<div class="empty">This project has no seats yet.</div>';document.querySelectorAll('[data-seat]').forEach(n=>{n.onclick=e=>{if(e.target.closest('[data-edit-seat]'))return;let id=n.dataset.seat;if(e.metaKey||e.ctrlKey){selected.has(id)?selected.delete(id):selected.add(id);return renderSeats()}selected=new Set([id]);let direct=project()?.sessions.find(x=>x.kind==='direct'&&x.participants[0]===id);if(direct){sessionId=direct.id;refresh()}};n.oncontextmenu=e=>{e.preventDefault();if(!selected.has(n.dataset.seat))selected=new Set([n.dataset.seat]);renderSeats();createSession()}});document.querySelectorAll('[data-edit-seat]').forEach(n=>n.onclick=e=>{e.stopPropagation();editSeat(n.dataset.editSeat)})}
function renderSessions(){let custom=(project()?.sessions||[]).filter(x=>x.kind==='custom'&&!x.archived);$('sessions').innerHTML=custom.map(s=>`<button class="overview-session" data-overview-session="${s.id}">${esc(s.name)} · ${s.participants.length} seats</button>`).join('')||'<span class="section-note">No custom sessions.</span>';document.querySelectorAll('[data-overview-session]').forEach(n=>n.onclick=()=>{sessionId=n.dataset.overviewSession;selected.clear();refresh()})}
function renderConversation(){let p=project(),s=session();$('projectOverview').hidden=!!s;$('conversationView').hidden=!s;$('sessionTitle').textContent=s?.name||'Project overview';$('participants').innerHTML=s?s.participants.map(id=>{let x=seat(id),m=x&&member(x.occupant);return x?`<span class="person"><i style="background:${m?.colour||'var(--seat)'}">${esc((x.name||'?')[0])}</i>${esc(x.name)}<small>${esc(x.role)}</small></span>`:''}).join(''):'';$('clearContext').disabled=!s||!!data.status?.busy?.length;$('sessionMenu').disabled=!s;if(!s){$('overviewTitle').textContent=p?.name||'Select a project';$('overviewMeta').textContent=p?`${p.state} · ${size(p.storage)} · ${(data.seats||[]).length} seats`:'';return}$('composer').style.display=p?.state==='open'&&!s.archived?'':'none';renderMessages(stickBottom)}
function messageColour(message){if(message.author==='lead')return colour(data.lead?.colour);let authorSeat=seat(message.author),author=authorSeat&&member(authorSeat.occupant);return colour(author?.colour)}
function colour(value){return /^#[0-9a-f]{6}$/i.test(value||'')?value:'var(--seat)'}
function renderMessages(toBottom=false){let messages=transcript||[],box=$('messages');box.innerHTML=!messages.length?'<div class="empty">This session is empty. Send a message to begin.</div>':`${hasOlder?'<div class="history-loader">Scroll up to load earlier messages</div>':''}`+messages.map(m=>m.kind==='boundary'||m.kind==='compaction'?`<div class="boundary ${m.kind==='compaction'?'compaction':''}"><span>${esc(m.text)}</span></div>`:`<article class="message ${m.kind==='error'?'error':''}"><div class="avatar" style="background:${messageColour(m)}">${esc((m.author_name||'?')[0])}</div><div><div class="meta"><b>${esc(m.author_name)}</b><time>${new Date(m.ts*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></div><div class="body">${format(m.text)}</div>${images(m)}</div></article>`).join('');if(toBottom)box.scrollTop=box.scrollHeight}
async function loadOlder(){if(loadingOlder||!hasOlder||!sessionId||!transcript.length)return;loadingOlder=true;let box=$('messages'),oldHeight=box.scrollHeight,oldTop=box.scrollTop,q=new URLSearchParams({project:projectId,session:sessionId,before:String(transcript[0].seq),limit:'60'});if($('search').value)q.set('search',$('search').value);try{let page=await api('/api/state?'+q),merged=new Map([...(page.messages||[]),...transcript].map(m=>[m.seq,m]));transcript=[...merged.values()].sort((a,b)=>a.seq-b.seq);data.messages=transcript;hasOlder=!!page.message_page?.has_more;renderMessages(false);box.scrollTop=box.scrollHeight-oldHeight+oldTop}catch(e){console.error(e)}finally{loadingOlder=false}}
function format(text){return esc(text).replace(/```([\s\S]*?)```/g,'<pre>$1</pre>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<b>$1</b>')}
function images(m){return (m.images||[]).length?`<div class="shots">${m.images.map(name=>`<img src="/api/files/${name}?project=${projectId}&session=${sessionId}">`).join('')}</div>`:''}
function size(n=0){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function form(title,html,onSave){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;$('dialogSave').disabled=false;let d=$('dialog');d.showModal();d.onclose=async()=>{if(d.returnValue!=='default')return;try{await onSave(new FormData(d.querySelector('form')));refresh()}catch(e){alert(e.message)}}}
function memberOptions(value=''){return `<option value="" ${!value?'selected':''}>Unassigned</option>`+(data.members||[]).map(m=>`<option value="${m.id}" ${m.id===value?'selected':''}>${esc(m.name)} · ${m.kind}</option>`).join('')}
function typeOptions(){return (data.project_types||[]).map(type=>`<option value="${type.id}" ${type.id==='type_blank'?'selected':''}>${esc(type.name)} · ${type.seat_templates.length} seats</option>`).join('')}
function newProject(){form('New project',`<label>Name<input name="name" required></label><label>Project type<select name="type_id">${typeOptions()}</select></label><label>Working folder<input name="cwd" placeholder="Use Sinaxa folder"></label>`,f=>api('/api/projects',{method:'POST',body:body({name:f.get('name'),cwd:f.get('cwd')||null,type_id:f.get('type_id')||null})}).then(x=>{projectId=x.project.id;sessionId=null}))}
function newSeat(){let used=new Set((data.seats||[]).map(s=>s.template_id)),available=(data.seat_templates||[]).filter(t=>!used.has(t.id));if(!available.length){form('Add seat','<p>Every seat from the global catalog is already used by this project. Create another definition in Seats first.</p>',()=>Promise.resolve());$('dialogSave').disabled=true;return}let first=available[0];form('Add seat',`<label>Seat definition<select name="template_id">${available.map(t=>`<option value="${t.id}">${esc(t.role)} · ${esc(t.category)}</option>`).join('')}</select></label><label>Member<select name="occupant">${memberOptions(first.default_agent)}</select></label><label>Project instructions<textarea name="prompt" required>${esc(first.prompt)}</textarea></label>`,f=>api('/api/seats',{method:'POST',body:body({project:projectId,template_id:f.get('template_id'),occupant:f.get('occupant')||null,prompt:f.get('prompt')})}));$('dialogSave').disabled=false;let picker=$('dialogBody').querySelector('[name="template_id"]');picker.onchange=()=>{let t=available.find(x=>x.id===picker.value);$('dialogBody').querySelector('[name="prompt"]').value=t.prompt;$('dialogBody').querySelector('[name="occupant"]').value=t.default_agent||''}}
function editSeat(id){let s=seat(id),template=(data.seat_templates||[]).find(t=>t.id===s.template_id);form('Edit project seat',`<label>Seat definition<input value="${esc(template?.role||s.role)}" disabled></label><label>Member<select name="occupant">${memberOptions(s.occupant)}</select></label><label>Project instructions<textarea name="prompt">${esc(s.prompt)}</textarea></label><label class="danger"><input type="checkbox" name="remove"> Remove this seat and its direct history</label>`,f=>f.get('remove')?api(`/api/seats/${id}?project=${projectId}`,{method:'DELETE'}):api('/api/seats/'+id,{method:'PATCH',body:body({project:projectId,occupant:f.get('occupant'),prompt:f.get('prompt')})}))}
function createSession(){if(!projectId)return;let picks=selected.size?[...selected]:(data.seats||[]).map(x=>x.id);form('New session',`<label>Name<input name="name" required></label><div>${(data.seats||[]).map(s=>`<label class="choice"><input type="checkbox" name="participants" value="${s.id}" ${picks.includes(s.id)?'checked':''}> ${esc(s.role)} · ${esc(s.name)}</label>`).join('')}</div>`,f=>api('/api/sessions',{method:'POST',body:body({project:projectId,name:f.get('name'),participants:f.getAll('participants')})}).then(x=>{sessionId=x.session.id;selected.clear()}))}
$('newProject').onclick=newProject;$('newSeat').onclick=newSeat;$('newSession').onclick=createSession;$('newSessionSmall').onclick=createSession;
$('openMain').onclick=()=>{let team=project()?.sessions.find(x=>x.kind==='team');if(team){sessionId=team.id;selected.clear();refresh()}};
$('toggleProject').onclick=async()=>{let p=project();await api('/api/projects/'+p.id,{method:'PATCH',body:body({state:p.state==='open'?'closed':'open'})});refresh()};
$('clearContext').onclick=async()=>{if(!sessionId)return;await api(`/api/sessions/${sessionId}/context`,{method:'POST',body:body({project:projectId})});await refresh()};
$('sessionMenu').onclick=()=>{let s=session();form('Manage session',`<p>${esc(s.name)} · ${size(s.storage)}</p><label>Agent response timeout (seconds)<input type="number" name="turn_timeout" min="30" max="7200" value="${s.turn_timeout||1800}"></label><label>Maximum agent turns per round<input type="number" name="max_agent_turns" min="1" max="100" value="${s.max_agent_turns||100}"></label>${s.kind==='custom'?'<label><input type="checkbox" name="archive" '+(s.archived?'checked':'')+'> Archived</label><label class="danger"><input type="checkbox" name="remove"> Delete session and history</label>':''}`,f=>{if(f.get('remove'))return api(`/api/sessions/${s.id}?project=${projectId}`,{method:'DELETE'}).then(()=>sessionId=null);return api('/api/sessions/'+s.id,{method:'PATCH',body:body({project:projectId,turn_timeout:+f.get('turn_timeout'),max_agent_turns:+f.get('max_agent_turns'),...(s.kind==='custom'?{archived:!!f.get('archive')}:{})})})})};
let searchTimer;$('search').oninput=()=>{clearTimeout(searchTimer);windowKey='';searchTimer=setTimeout(refresh,250)};
$('messages').onscroll=()=>{if($('messages').scrollTop<80)loadOlder()};
$('attach').onclick=()=>$('files').click();$('files').onchange=()=>{pending.push(...$('files').files);renderAttachments()};function renderAttachments(){$('attachments').innerHTML=pending.map((f,i)=>`<span class="attachment">${esc(f.name)} <button data-drop="${i}">×</button></span>`).join('');document.querySelectorAll('[data-drop]').forEach(x=>x.onclick=()=>{pending.splice(+x.dataset.drop,1);renderAttachments()})}
document.querySelectorAll('[data-format]').forEach(b=>b.onclick=()=>{let t=$('message'),mark=b.dataset.format,a=t.selectionStart,z=t.selectionEnd;t.setRangeText(mark+t.value.slice(a,z)+mark,a,z,'end');t.focus()});
function readFile(file){return new Promise((ok,bad)=>{let r=new FileReader;r.onload=()=>ok({type:file.type,data:r.result.split(',')[1]});r.onerror=bad;r.readAsDataURL(file)})}
$('send').onclick=async()=>{let text=$('message').value.trim();if(!text&&!pending.length)return;let images=await Promise.all(pending.map(readFile));$('message').value='';pending=[];renderAttachments();await api('/api/say',{method:'POST',body:body({project:projectId,session:sessionId,text,images})});refresh();startPoll()};$('message').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('send').click()}};
function startPoll(){clearInterval(poll);let quiet=0;poll=setInterval(async()=>{let before=(data.messages||[]).length;await refresh();let busy=data.status?.busy?.length;if(!busy&&(data.messages||[]).length===before)quiet++;else quiet=0;if(quiet>2){clearInterval(poll);poll=null}},800)}
refresh();
document.addEventListener('click',e=>{if(e.target.matches('dialog button[value="cancel"]')){e.preventDefault();e.target.closest('dialog').close('cancel')}});
