document.documentElement.dataset.theme=localStorage.getItem('sinaxa-theme')||'dark';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
let data={},projectId=null,sessionId=null,selected=new Set(),pending=[],poll=null;
let transcript=[],hasOlder=false,hasNewer=false,windowKey='',loadingOlder=false,loadingNewer=false,stickBottom=true,scrollAnchor=null,markingRead=false;
const project=()=>data.projects?.find(x=>x.id===projectId), session=()=>project()?.sessions.find(x=>x.id===sessionId);
const member=id=>data.members?.find(x=>x.id===id), seat=id=>data.seats?.find(x=>x.id===id);
async function api(path,options={}){let r=await fetch(path,{headers:{'Content-Type':'application/json'},...options});let payload=await r.json();if(!r.ok)throw Error(payload.error||r.statusText);return payload}
function body(value){return JSON.stringify(value)}
async function refresh(){let box=$('messages'),nearBottom=!box||box.scrollHeight-box.scrollTop-box.clientHeight<120,key=`${projectId||''}:${sessionId||''}:${$('search').value}`,current=session(),openingUnread=key!==windowKey&&current?.unread>0&&!$('search').value,q=new URLSearchParams();if(projectId)q.set('project',projectId);if(sessionId)q.set('session',sessionId);if($('search').value)q.set('search',$('search').value);if(openingUnread)q.set('anchor',String(current.read_seq||0));q.set('limit','60');let fresh=await api('/api/state?'+q);data=fresh;if(!projectId&&data.projects?.length)projectId=data.projects[0].id;let p=project();if(sessionId&&!p?.sessions.some(x=>x.id===sessionId))sessionId=null;if(projectId&&data.project!==projectId)return refresh();if(sessionId&&data.session!==sessionId)return refresh();key=`${projectId||''}:${sessionId||''}:${$('search').value}`;if(key!==windowKey){transcript=[...(fresh.messages||[])];hasOlder=!!fresh.message_page?.has_more;hasNewer=!!fresh.message_page?.has_newer;windowKey=key;stickBottom=!openingUnread;scrollAnchor=openingUnread?(current?.read_seq||0):null}else{let earliest=transcript[0]?.seq,latestOld=fresh.messages?.[0]?.seq,merged=new Map([...transcript,...(fresh.messages||[])].map(m=>[m.seq,m]));transcript=[...merged.values()].sort((a,b)=>a.seq-b.seq);if(earliest==null||latestOld==null||earliest>=latestOld)hasOlder=!!fresh.message_page?.has_more;hasNewer=!!fresh.message_page?.has_newer;stickBottom=nearBottom}data.messages=transcript;render()}
function render(){renderProjects();renderSeats();renderSessions();renderConversation()}
