function size(n=0){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
function form(title,html,onSave,saveLabel='Save'){$('dialogTitle').textContent=title;$('dialogBody').innerHTML=html;$('dialogSave').textContent=saveLabel;$('dialogSave').disabled=false;let d=$('dialog');d.showModal();d.onclose=async()=>{if(d.returnValue!=='default')return;try{await onSave(new FormData(d.querySelector('form')));windowKey='';refresh()}catch(e){alert(e.message)}}}
function clearContextSection(seq){form('Delete cleared context history','<p>This permanently deletes only the messages and attachments before this context separator. The active context and later history are kept.</p>',()=>api(`/api/sessions/${sessionId}/history`,{method:'POST',body:body({project:projectId,boundary_seq:seq})}),'Delete history')}
function clearAllClosedHistory(){let s=session();if(!s?.closed_contexts)return;form('Delete all cleared context history','<p>This permanently deletes every context section previously closed with Clear context. The current active context is kept.</p>',()=>api(`/api/sessions/${sessionId}/history`,{method:'POST',body:body({project:projectId})}),'Delete history')}
function memberOptions(value=''){return `<option value="" ${!value?'selected':''}>Unassigned</option>`+(data.members||[]).map(m=>`<option value="${m.id}" ${m.id===value?'selected':''}>${esc(m.name)} · ${m.kind}</option>`).join('')}
function typeOptions(){return (data.project_types||[]).map(type=>`<option value="${type.id}" ${type.id==='type_blank'?'selected':''}>${esc(type.name)} · ${type.seat_templates.length} seats</option>`).join('')}
function newProject(){form('New project',`<label>Name<input name="name" required></label><label>Project type<select name="type_id">${typeOptions()}</select></label><label>Working folder<input name="cwd" placeholder="Use Sinaxa folder"></label>`,f=>api('/api/projects',{method:'POST',body:body({name:f.get('name'),cwd:f.get('cwd')||null,type_id:f.get('type_id')||null})}).then(x=>{projectId=x.project.id;sessionId=null}))}
function newSeat(){let used=new Set((data.seats||[]).map(s=>s.template_id)),available=(data.seat_templates||[]).filter(t=>!used.has(t.id));if(!available.length){form('Add seat','<p>Every seat from the global catalog is already used by this project. Create another definition in Seats first.</p>',()=>Promise.resolve());$('dialogSave').disabled=true;return}let first=available[0];form('Add seat',`<label>Seat definition<select name="template_id">${available.map(t=>`<option value="${t.id}">${esc(t.role)} · ${esc(t.category)}</option>`).join('')}</select></label><label>Member<select name="occupant">${memberOptions(first.default_agent)}</select></label><label>Project instructions<textarea name="prompt" required>${esc(first.prompt)}</textarea></label>`,f=>api('/api/seats',{method:'POST',body:body({project:projectId,template_id:f.get('template_id'),occupant:f.get('occupant')||null,prompt:f.get('prompt')})}));$('dialogSave').disabled=false;let picker=$('dialogBody').querySelector('[name="template_id"]');picker.onchange=()=>{let t=available.find(x=>x.id===picker.value);$('dialogBody').querySelector('[name="prompt"]').value=t.prompt;$('dialogBody').querySelector('[name="occupant"]').value=t.default_agent||''}}
function editSeat(id){let s=seat(id),template=(data.seat_templates||[]).find(t=>t.id===s.template_id);form('Edit project seat',`<label>Seat definition<input value="${esc(template?.role||s.role)}" disabled></label><label>Member<select name="occupant">${memberOptions(s.occupant)}</select></label><label>Project instructions<textarea name="prompt">${esc(s.prompt)}</textarea></label><label class="danger"><input type="checkbox" name="remove"> Remove this seat and its direct history</label>`,f=>f.get('remove')?api(`/api/seats/${id}?project=${projectId}`,{method:'DELETE'}):api('/api/seats/'+id,{method:'PATCH',body:body({project:projectId,occupant:f.get('occupant'),prompt:f.get('prompt')})}))}
function createSession(){if(!projectId)return;let picks=selected.size?[...selected]:(data.seats||[]).map(x=>x.id);form('New session',`<label>Name<input name="name" required></label><div>${(data.seats||[]).map(s=>`<label class="choice"><input type="checkbox" name="participants" value="${s.id}" ${picks.includes(s.id)?'checked':''}> ${esc(s.role)} · ${esc(s.name)}</label>`).join('')}</div>`,f=>api('/api/sessions',{method:'POST',body:body({project:projectId,name:f.get('name'),participants:f.getAll('participants')})}).then(x=>{sessionId=x.session.id;selected.clear()}))}
